export const PROFILE_FEED_CONNECT = 'PROFILE_FEED_CONNECT';
export const PROFILE_FEED_DISCONNECT = 'PROFILE_FEED_DISCONNECT';
export const PROFILE_FEED_WS_CONNECTING = 'PROFILE_FEED_WS_CONNECTING';
export const PROFILE_FEED_WS_OPEN = 'PROFILE_FEED_WS_OPEN';
export const PROFILE_FEED_WS_CLOSE = 'PROFILE_FEED_WS_CLOSE';
export const PROFILE_FEED_WS_MESSAGE = 'PROFILE_FEED_WS_MESSAGE';
export const PROFILE_FEED_WS_ERROR = 'PROFILE_FEED_WS_ERROR';

export const connect = (url) => ({
    type: PROFILE_FEED_CONNECT,
    payload: url
});

export const disconnect = () => ({
    type: PROFILE_FEED_DISCONNECT,
});
